services:
  db:
    image: mysql:latest
    container_name: wikigroup
    environment:
      MYSQL_ROOT_PASSWORD: Narelo12%
      MYSQL_DATABASE: wikigroup
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: wikigroup-app
    ports:
      - "8080:8080"